### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by MrAnonymousse** [noptrix/sshprank#20]
`./sshprank.py rank -b hosts.txt > sshds2.txt

[+] game started
[+] cracking single target
[+] game over
Traceback (most recent call last):
  File "/root/sshprank/./sshprank.py", line 720, in <module>
    main(sys.argv[1:])
  File "/root/sshprank/./sshprank.py", line 667, in main
    crack_single()
  File "/root/sshprank/./sshprank.py", line 534, in crack_single
    host, ports = list(opts['targets'].copy().items())[0]
AttributeError: 'list' object has no attribute 'items'`

No matter what order you place, the same error occurs.
I know there is already another issue on the same error, but the error is not fixed.

**Comment by noptrix** [comment]
@MrAnonymousse ACK. i will fix those bugs soon.

**Comment by noptrix** [comment]
@MrAnonymousse should be fixed in https://github.com/noptrix/sshprank/commit/057db39cac02d402bc326201481de458e73c330d - feel free to re-open, if not.
