### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'`

### ISSUE THREAD

**Issue by Nukerzz** [noptrix/sshprank#21]
[+] game started
[+] cracking single target
[+] game over
Traceback (most recent call last):
File "/root/sshprank/./sshprank.py", line 720, in
main(sys.argv[1:])
File "/root/sshprank/./sshprank.py", line 667, in main
crack_single()
File "/root/sshprank/./sshprank.py", line 534, in crack_single
host, ports = list(opts['targets'].copy().items())[0]
AttributeError: 'list' object has no attribute 'items'`

**Comment by noptrix** [comment]
@agar712 thanks. yes same like #20 - everythign will be fixed soon. closing this issue here as we got it on #20
