### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by vargas2000** [noptrix/sshprank#24]
awa@awa:~/sshprank$ sudo ./sshprank.py -m '-p22 --rate=10000 -iL a.txt' -u admin -p admin -x 100 -X 100 -o global.txt
              __                           __
   __________/ /_  ____  _________ _____  / /__
  / ___/ ___/ __ \/ __ \/ ___/ __ `/ __ \/ //_/
 (__  |__  ) / / / /_/ / /  / /_/ / / / / ,<
/____/____/_/ /_/ .___/_/   \__,_/_/ /_/_/|_|
               /_/

      --== [ by nullsecurity.net ] ==--

[+] game started
[+] scanning and cracking targets
[/] scanning sshds
[+] game over
Traceback (most recent call last):
  File "./sshprank.py", line 720, in <module>
    main(sys.argv[1:])
  File "./sshprank.py", line 681, in main
    crack_scan()
  File "./sshprank.py", line 577, in crack_scan
    targets = grep_service(future.result())
  File "./sshprank.py", line 372, in grep_service
    for h in scan.scan_result['scan'].keys():
TypeError: string indices must be integers

**Comment by noptrix** [comment]
fixed. if not, re-open:)
